/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package help;

import javax.swing.*;

/**
 *
 * @author Dammar
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Help() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ropaLabel1 = new utils.helper.RopaLabel();
        pHelp = new utils.helper.RoundedPanel();
        faq = new utils.helper.RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        roundedPanel1 = new utils.helper.RoundedPanel();
        phSearch = new utils.helper.RopaLabel();
        tfSearch = new javax.swing.JTextField();
        myAccount = new utils.helper.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        about = new utils.helper.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        guide = new utils.helper.RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        announcement = new utils.helper.RoundedPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        feedback = new utils.helper.RoundedPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1281, 650));

        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 650));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/utils/logo.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 200, -1));

        ropaLabel1.setText("Tactic's");
        ropaLabel1.setFontSize(24.0F);
        main.add(ropaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        pHelp.setBackground(new java.awt.Color(123, 15, 58));
        pHelp.setPreferredSize(new java.awt.Dimension(280, 280));
        pHelp.setRoundBottomLeft(20);
        pHelp.setRoundBottomRight(20);
        pHelp.setRoundTopLeft(20);
        pHelp.setRoundTopRight(20);
        pHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faq.setBackground(new java.awt.Color(202, 28, 77));
        faq.setPreferredSize(new java.awt.Dimension(280, 280));
        faq.setRoundBottomLeft(50);
        faq.setRoundBottomRight(50);
        faq.setRoundTopLeft(50);
        faq.setRoundTopRight(50);
        faq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FAQ");
        faq.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/faq.png"))); // NOI18N
        faq.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 110));

        pHelp.add(faq, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 150, 150));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("How can we help?");
        pHelp.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 30));

        roundedPanel1.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phSearch.setForeground(new java.awt.Color(123, 15, 58));
        phSearch.setText("Search");
        phSearch.setFontSize(18.0F);
        roundedPanel1.add(phSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        tfSearch.setBackground(new java.awt.Color(217, 217, 217));
        tfSearch.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(123, 15, 58));
        tfSearch.setBorder(null);
        tfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSearchFocusLost(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        roundedPanel1.add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, 30));

        pHelp.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 449, 46));

        myAccount.setBackground(new java.awt.Color(202, 28, 77));
        myAccount.setPreferredSize(new java.awt.Dimension(280, 280));
        myAccount.setRoundBottomLeft(50);
        myAccount.setRoundBottomRight(50);
        myAccount.setRoundTopLeft(50);
        myAccount.setRoundTopRight(50);
        myAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Account");
        myAccount.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/My_account.png"))); // NOI18N
        myAccount.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 80));

        pHelp.add(myAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 150));

        about.setBackground(new java.awt.Color(202, 28, 77));
        about.setPreferredSize(new java.awt.Dimension(280, 280));
        about.setRoundBottomLeft(50);
        about.setRoundBottomRight(50);
        about.setRoundTopLeft(50);
        about.setRoundTopRight(50);
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("About");
        about.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/about.png"))); // NOI18N
        about.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 100));

        pHelp.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, 150));

        guide.setBackground(new java.awt.Color(202, 28, 77));
        guide.setPreferredSize(new java.awt.Dimension(280, 280));
        guide.setRoundBottomLeft(50);
        guide.setRoundBottomRight(50);
        guide.setRoundTopLeft(50);
        guide.setRoundTopRight(50);
        guide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Guide");
        guide.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/guild2.png"))); // NOI18N
        guide.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 100));

        pHelp.add(guide, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 150, 150));

        announcement.setBackground(new java.awt.Color(202, 28, 77));
        announcement.setPreferredSize(new java.awt.Dimension(280, 280));
        announcement.setRoundBottomLeft(50);
        announcement.setRoundBottomRight(50);
        announcement.setRoundTopLeft(50);
        announcement.setRoundTopRight(50);
        announcement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Announcement");
        announcement.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/announcement.png"))); // NOI18N
        announcement.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 120));

        pHelp.add(announcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 150, 150));

        feedback.setBackground(new java.awt.Color(202, 28, 77));
        feedback.setPreferredSize(new java.awt.Dimension(280, 280));
        feedback.setRoundBottomLeft(50);
        feedback.setRoundBottomRight(50);
        feedback.setRoundTopLeft(50);
        feedback.setRoundTopRight(50);
        feedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Feedback");
        feedback.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/feedback.png"))); // NOI18N
        feedback.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 120));

        pHelp.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 150, 150));

        main.add(pHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 660, 530));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/utils/bg.png"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(0, 0));
        bg.setMinimumSize(new java.awt.Dimension(0, 0));
        main.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, 1020));

        jMenu2.setText("Account");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusGained
        // TODO add your handling code here:
        phSearch.setVisible(false);
    }//GEN-LAST:event_tfSearchFocusGained

    private void tfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusLost
        // TODO add your handling code here:
        if (tfSearch.getText().isEmpty())
        phSearch.setVisible(true);
    }//GEN-LAST:event_tfSearchFocusLost

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.helper.RoundedPanel about;
    private utils.helper.RoundedPanel announcement;
    private javax.swing.JLabel bg;
    private utils.helper.RoundedPanel faq;
    private utils.helper.RoundedPanel feedback;
    private utils.helper.RoundedPanel guide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel main;
    private utils.helper.RoundedPanel myAccount;
    private utils.helper.RoundedPanel pHelp;
    private utils.helper.RopaLabel phSearch;
    private utils.helper.RopaLabel ropaLabel1;
    private utils.helper.RoundedPanel roundedPanel1;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
