/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editProfile;

import auth.DatabaseConnection;
import java.sql.PreparedStatement;
import java.sql.Connection;
import home.Home;
import javax.swing.*;
import myAccount.MyAccount;
import java.awt.Cursor;
import utils.helper.Session;
import java.sql.ResultSet;

/**
 *
 * @author Dammar
 */
public class Edit_profile extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Edit_profile() {
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        nickname.setText(Session.getUsername());
        tfUsername.setText(Session.getUsername());
        tfEmail.setText(Session.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        roundedPanel9 = new utils.helper.RoundedPanel();
        roundedPanel10 = new utils.helper.RoundedPanel();
        phEmail = new utils.helper.RopaLabel();
        tfEmail = new javax.swing.JTextField();
        email = new utils.helper.RopaLabel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel5 = new utils.helper.RoundedPanel();
        roundedPanel6 = new utils.helper.RoundedPanel();
        phPassword = new utils.helper.RopaLabel();
        tfPassword = new javax.swing.JPasswordField();
        Password = new utils.helper.RopaLabel();
        roundedPanel7 = new utils.helper.RoundedPanel();
        roundedPanel8 = new utils.helper.RoundedPanel();
        tfUsername = new javax.swing.JTextField();
        username = new utils.helper.RopaLabel();
        nickname = new utils.helper.RopaLabel();
        back = new utils.helper.RoundedPanel();
        ropaLabel1 = new utils.helper.RopaLabel();
        ropaLabel2 = new utils.helper.RopaLabel();
        home_path = new utils.helper.RopaLabel();
        EditProfile_path = new utils.helper.RopaLabel();
        myAccount_path = new utils.helper.RopaLabel();
        Save = new utils.helper.RoundedPanel();
        ropaLabel3 = new utils.helper.RopaLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1281, 650));
        setResizable(false);

        main.setBackground(new java.awt.Color(8, 18, 38));
        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 650));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel9.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel9.setRoundBottomLeft(20);
        roundedPanel9.setRoundBottomRight(20);
        roundedPanel9.setRoundTopLeft(20);
        roundedPanel9.setRoundTopRight(20);
        roundedPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel10.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel10.setRoundBottomLeft(20);
        roundedPanel10.setRoundBottomRight(20);
        roundedPanel10.setRoundTopLeft(20);
        roundedPanel10.setRoundTopRight(20);
        roundedPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phEmail.setForeground(new java.awt.Color(123, 15, 58));
        phEmail.setText("Example@gmail.com");
        phEmail.setFontSize(18.0F);
        roundedPanel10.add(phEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 40));

        tfEmail.setBackground(new java.awt.Color(217, 217, 217));
        tfEmail.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(123, 15, 58));
        tfEmail.setBorder(null);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        roundedPanel10.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        roundedPanel9.add(roundedPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        email.setText("Email");
        email.setFontSize(18.0F);
        roundedPanel9.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 580, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/character/128x128/dragunov_circle.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        roundedPanel5.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel5.setRoundBottomLeft(20);
        roundedPanel5.setRoundBottomRight(20);
        roundedPanel5.setRoundTopLeft(20);
        roundedPanel5.setRoundTopRight(20);
        roundedPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel6.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel6.setRoundBottomLeft(20);
        roundedPanel6.setRoundBottomRight(20);
        roundedPanel6.setRoundTopLeft(20);
        roundedPanel6.setRoundTopRight(20);
        roundedPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phPassword.setForeground(new java.awt.Color(123, 15, 58));
        phPassword.setText("**********");
        phPassword.setFontSize(18.0F);
        roundedPanel6.add(phPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tfPassword.setBackground(new java.awt.Color(217, 217, 217));
        tfPassword.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(123, 15, 58));
        tfPassword.setBorder(null);
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        roundedPanel6.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 370, -1));

        roundedPanel5.add(roundedPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        Password.setText("Password");
        Password.setFontSize(18.0F);
        roundedPanel5.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 580, 60));

        roundedPanel7.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel7.setRoundBottomLeft(20);
        roundedPanel7.setRoundBottomRight(20);
        roundedPanel7.setRoundTopLeft(20);
        roundedPanel7.setRoundTopRight(20);
        roundedPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel8.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel8.setRoundBottomLeft(20);
        roundedPanel8.setRoundBottomRight(20);
        roundedPanel8.setRoundTopLeft(20);
        roundedPanel8.setRoundTopRight(20);
        roundedPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setBackground(new java.awt.Color(217, 217, 217));
        tfUsername.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(123, 15, 58));
        tfUsername.setBorder(null);
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        roundedPanel8.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        roundedPanel7.add(roundedPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        username.setText("Username");
        username.setFontSize(18.0F);
        roundedPanel7.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 580, 60));

        nickname.setText("Nickname");
        nickname.setFontSize(20.0F);
        main.add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 80, 30));

        back.setBackground(new java.awt.Color(123, 15, 58));
        back.setRoundBottomLeft(10);
        back.setRoundBottomRight(10);
        back.setRoundTopLeft(10);
        back.setRoundTopRight(10);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });

        ropaLabel1.setText("Back");
        ropaLabel1.setFontSize(15.0F);

        ropaLabel2.setText("«");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ropaLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ropaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ropaLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(backLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ropaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        main.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 60, 30));

        home_path.setText("Home  / ");
        home_path.setFontSize(20.0F);
        home_path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_pathMouseEntered(evt);
            }
        });
        main.add(home_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, -1));

        EditProfile_path.setText("/ Edit Profile");
        EditProfile_path.setFontSize(20.0F);
        main.add(EditProfile_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 100, -1));

        myAccount_path.setText(" My Account");
        myAccount_path.setFontSize(20.0F);
        myAccount_path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myAccount_pathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myAccount_pathMouseEntered(evt);
            }
        });
        main.add(myAccount_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, -1));

        Save.setBackground(new java.awt.Color(123, 15, 58));
        Save.setRoundBottomLeft(20);
        Save.setRoundBottomRight(20);
        Save.setRoundTopLeft(20);
        Save.setRoundTopRight(20);
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });

        ropaLabel3.setText("Save");
        ropaLabel3.setFontSize(20.0F);

        javax.swing.GroupLayout SaveLayout = new javax.swing.GroupLayout(Save);
        Save.setLayout(SaveLayout);
        SaveLayout.setHorizontalGroup(
            SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ropaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        SaveLayout.setVerticalGroup(
            SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ropaLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        main.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 80, 40));

        jMenu2.setText("Account");

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
//        phUsername.setVisible(false);
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
//        if (tfUsername.getText().isEmpty())
//            phUsername.setVisible(true);
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
//         TODO add your handling code here:
        phPassword.setVisible(false);
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if (tfPassword.getPassword() == null || tfPassword.getPassword().length == 0)
            phPassword.setVisible(true);
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        // TODO add your handling code here:
        phEmail.setVisible(false);
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
        if (tfEmail.getText().isEmpty())
            phEmail.setVisible(true);
    }//GEN-LAST:event_tfEmailFocusLost

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_tfEmailActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        MyAccount myAccount = new MyAccount();
        myAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void home_pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_pathMouseClicked

    private void home_pathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseEntered
        // TODO add your handling code here:
        home_path.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_home_pathMouseEntered

    private void myAccount_pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccount_pathMouseClicked
        // TODO add your handling code here:
        MyAccount myAccount = new MyAccount();
        myAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myAccount_pathMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void myAccount_pathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccount_pathMouseEntered
        // TODO add your handling code here:
        myAccount_path.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myAccount_pathMouseEntered

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        // TODO add your handling code here:
        String newEmail = tfEmail.getText();
        String newPassword = new String(tfPassword.getPassword());
        String newUsername = tfUsername.getText();
        String currentUsername = Session.getUsername();

        // Validasi input kosong
        if (newUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username harus diisi!");
            return;
        }

        if (newEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email harus diisi!");
            return;
        }

        // Validasi format email
        if (!newEmail.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid!");
            return;
        }

        try (Connection conn = DatabaseConnection.getConnection()) {

            String fetchQuery = "SELECT password FROM user WHERE username = ?";
            PreparedStatement fetchStmt = conn.prepareStatement(fetchQuery);
            fetchStmt.setString(1, currentUsername);
            ResultSet rs = fetchStmt.executeQuery();

            String oldPassword = "";
            if (rs.next()) {
                oldPassword = rs.getString("password");
            } else {
                JOptionPane.showMessageDialog(this, "Data pengguna tidak ditemukan!");
                return;
            }

            if (newPassword.isEmpty()) {
                newPassword = oldPassword;
            }

            // Query untuk update email dan password
            String query = "UPDATE user SET email = ?, password = ?, username = ? WHERE username = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, newEmail);
            stmt.setString(2, newPassword);
            stmt.setString(3, newUsername);
            stmt.setString(4, currentUsername);

            // Eksekusi query
            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Perubahan berhasil disimpan!");

                // Perbarui sesi email dengan email baru
                Session.setSession(newUsername, newEmail);

            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data. Username tidak ditemukan.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }

    }//GEN-LAST:event_SaveMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.helper.RopaLabel EditProfile_path;
    private utils.helper.RopaLabel Password;
    private utils.helper.RoundedPanel Save;
    private utils.helper.RoundedPanel back;
    private utils.helper.RopaLabel email;
    private utils.helper.RopaLabel home_path;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel main;
    private utils.helper.RopaLabel myAccount_path;
    private utils.helper.RopaLabel nickname;
    private utils.helper.RopaLabel phEmail;
    private utils.helper.RopaLabel phPassword;
    private utils.helper.RopaLabel ropaLabel1;
    private utils.helper.RopaLabel ropaLabel2;
    private utils.helper.RopaLabel ropaLabel3;
    private utils.helper.RoundedPanel roundedPanel10;
    private utils.helper.RoundedPanel roundedPanel5;
    private utils.helper.RoundedPanel roundedPanel6;
    private utils.helper.RoundedPanel roundedPanel7;
    private utils.helper.RoundedPanel roundedPanel8;
    private utils.helper.RoundedPanel roundedPanel9;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private utils.helper.RopaLabel username;
    // End of variables declaration//GEN-END:variables
}
