/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editProfile;

import javax.swing.*;

/**
 *
 * @author Dammar
 */
public class Edit_profile extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Edit_profile() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        roundedPanel9 = new utils.helper.RoundedPanel();
        roundedPanel10 = new utils.helper.RoundedPanel();
        phEmail = new utils.helper.RopaLabel();
        tfEmail = new javax.swing.JTextField();
        email = new utils.helper.RopaLabel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel5 = new utils.helper.RoundedPanel();
        roundedPanel6 = new utils.helper.RoundedPanel();
        phPassword = new utils.helper.RopaLabel();
        tfPassword = new javax.swing.JPasswordField();
        Password = new utils.helper.RopaLabel();
        roundedPanel7 = new utils.helper.RoundedPanel();
        roundedPanel8 = new utils.helper.RoundedPanel();
        phUsername = new utils.helper.RopaLabel();
        tfUsername = new javax.swing.JTextField();
        username = new utils.helper.RopaLabel();
        jLabel18 = new javax.swing.JLabel();
        nickname1 = new utils.helper.RopaLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1281, 650));

        main.setBackground(new java.awt.Color(8, 18, 38));
        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 650));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel9.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel9.setRoundBottomLeft(20);
        roundedPanel9.setRoundBottomRight(20);
        roundedPanel9.setRoundTopLeft(20);
        roundedPanel9.setRoundTopRight(20);
        roundedPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel10.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel10.setRoundBottomLeft(20);
        roundedPanel10.setRoundBottomRight(20);
        roundedPanel10.setRoundTopLeft(20);
        roundedPanel10.setRoundTopRight(20);
        roundedPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phEmail.setForeground(new java.awt.Color(123, 15, 58));
        phEmail.setText("Example@gmail.com");
        phEmail.setFontSize(18.0F);
        roundedPanel10.add(phEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 40));

        tfEmail.setBackground(new java.awt.Color(217, 217, 217));
        tfEmail.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(123, 15, 58));
        tfEmail.setBorder(null);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        roundedPanel10.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        roundedPanel9.add(roundedPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        email.setText("Email");
        email.setFontSize(18.0F);
        roundedPanel9.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 580, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/character/128x128/dragunov_circle.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        roundedPanel5.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel5.setRoundBottomLeft(20);
        roundedPanel5.setRoundBottomRight(20);
        roundedPanel5.setRoundTopLeft(20);
        roundedPanel5.setRoundTopRight(20);
        roundedPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel6.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel6.setRoundBottomLeft(20);
        roundedPanel6.setRoundBottomRight(20);
        roundedPanel6.setRoundTopLeft(20);
        roundedPanel6.setRoundTopRight(20);
        roundedPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phPassword.setForeground(new java.awt.Color(123, 15, 58));
        phPassword.setText("**********");
        phPassword.setFontSize(18.0F);
        roundedPanel6.add(phPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tfPassword.setBackground(new java.awt.Color(217, 217, 217));
        tfPassword.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(123, 15, 58));
        tfPassword.setBorder(null);
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        roundedPanel6.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 370, -1));

        roundedPanel5.add(roundedPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        Password.setText("Password");
        Password.setFontSize(18.0F);
        roundedPanel5.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 580, 60));

        roundedPanel7.setBackground(new java.awt.Color(123, 15, 58));
        roundedPanel7.setRoundBottomLeft(20);
        roundedPanel7.setRoundBottomRight(20);
        roundedPanel7.setRoundTopLeft(20);
        roundedPanel7.setRoundTopRight(20);
        roundedPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel8.setBackground(new java.awt.Color(217, 217, 217));
        roundedPanel8.setRoundBottomLeft(20);
        roundedPanel8.setRoundBottomRight(20);
        roundedPanel8.setRoundTopLeft(20);
        roundedPanel8.setRoundTopRight(20);
        roundedPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phUsername.setForeground(new java.awt.Color(123, 15, 58));
        phUsername.setText("Nickname");
        phUsername.setFontSize(18.0F);
        roundedPanel8.add(phUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 40));

        tfUsername.setBackground(new java.awt.Color(217, 217, 217));
        tfUsername.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(123, 15, 58));
        tfUsername.setBorder(null);
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        roundedPanel8.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        roundedPanel7.add(roundedPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 449, 40));

        username.setText("Username");
        username.setFontSize(18.0F);
        roundedPanel7.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 40));

        main.add(roundedPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 580, 60));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Home/My Account/Edit Profile");
        main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 180, 30));

        nickname1.setText("Nickname");
        nickname1.setFontSize(20.0F);
        main.add(nickname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 80, 30));

        jMenu2.setText("Account");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        phUsername.setVisible(false);
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if (tfUsername.getText().isEmpty())
            phUsername.setVisible(true);
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        phPassword.setVisible(false);
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if (tfPassword.getPassword() == null || tfPassword.getPassword().length == 0)
        phPassword.setVisible(true);
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        // TODO add your handling code here:
        phEmail.setVisible(false);
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
        if (tfEmail.getText().isEmpty())
            phEmail.setVisible(true);
    }//GEN-LAST:event_tfEmailFocusLost

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.helper.RopaLabel Password;
    private utils.helper.RopaLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel main;
    private utils.helper.RopaLabel nickname1;
    private utils.helper.RopaLabel phEmail;
    private utils.helper.RopaLabel phPassword;
    private utils.helper.RopaLabel phUsername;
    private utils.helper.RoundedPanel roundedPanel10;
    private utils.helper.RoundedPanel roundedPanel5;
    private utils.helper.RoundedPanel roundedPanel6;
    private utils.helper.RoundedPanel roundedPanel7;
    private utils.helper.RoundedPanel roundedPanel8;
    private utils.helper.RoundedPanel roundedPanel9;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private utils.helper.RopaLabel username;
    // End of variables declaration//GEN-END:variables
}
