/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package combolist;

import auth.DatabaseConnection;
import guide.*;
import home.Home;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.helper.Db;
import utils.helper.ScrollBar;

/**
 *
 * @author Dammar
 */
public class ComboList extends javax.swing.JFrame {

    /**
     * Creates new form Guide
     */
    private void reloadPanel(JPanel panel) {
        panel.revalidate();
        panel.repaint();
    }

    private void updatePanel(JPanel panel, int x, int y, int w, int h) {
        panel.setPreferredSize(new java.awt.Dimension(w, h));
        panel.setBounds(x, y, w, h);
        reloadPanel(panel);
    }

    private void addAnchor(utils.helper.CharacterItem item, Object[] data) {
        item.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                combolist.Character character;
//                try {
//                    character = new Character(data);
//                    character.setVisible(true);
//                } catch (SQLException err) {
//                    err.printStackTrace();
//                }
//                dispose();

                Character character = new Character();
                character.setVisible(true);
                dispose();

            }

            @Override
            public void mouseEntered(MouseEvent e) {
                item.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
    }

    private void addCharacter(ArrayList<Object[]> data) {
        int row = (int) Math.ceil(data.size() / 8.0);
        int characterPanelHeight = 200 * row + (row * 10);
        int rootPanelHeight = characterPanelHeight + 80;
        for (Object[] pair : data) {
            utils.helper.CharacterItem item = new utils.helper.CharacterItem((String) pair[1], (String) pair[0]);
            character_list.add(item);
            addAnchor(item, pair);
        }
        updatePanel(character_list, character_list.getX(), character_list.getY(), 1170, characterPanelHeight);
        updatePanel(main, 0, 0, main.getWidth(), rootPanelHeight);
        updatePanel(root, 0, 0, root.getWidth(), rootPanelHeight);
    }

    public ComboList() {
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        Db db = new Db();
        ArrayList<Object[]> list = new ArrayList<>();
        try {
            db.connect();
            String selectQuery = "SELECT * FROM `character` WHERE `tier` != '-'";
            ResultSet resultSet = db.executeQuery(selectQuery);
            while (resultSet.next()) {
                String code = resultSet.getString("code");
                String name = resultSet.getString("name");
                list.add(new Object[]{code, name});
            }
            addCharacter(list);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                db.disconnect();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
//        addCharacter(60);
        ScrollBar scrollPane = new ScrollBar(root);
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBar(null);
        scrollPane.getVerticalScrollBar().setUnitIncrement(10);
        scrollPane.setBounds(0, 0, main.getWidth(), 650);
        add(scrollPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        home_path = new utils.helper.RopaLabel();
        guide_path1 = new utils.helper.RopaLabel();
        character_list = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        root.setMinimumSize(new java.awt.Dimension(1281, 100));
        root.setPreferredSize(new java.awt.Dimension(1281, 650));
        root.setLayout(new javax.swing.BoxLayout(root, javax.swing.BoxLayout.LINE_AXIS));

        main.setBackground(new java.awt.Color(8, 18, 38));
        main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 1480));
        main.setLayout(null);

        home_path.setText("Home  / ");
        home_path.setFontSize(20.0F);
        home_path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_pathMouseEntered(evt);
            }
        });
        main.add(home_path);
        home_path.setBounds(50, 50, 62, 22);

        guide_path1.setText(" Combo List");
        guide_path1.setFontSize(20.0F);
        main.add(guide_path1);
        guide_path1.setBounds(110, 50, 110, 22);

        character_list.setBackground(new java.awt.Color(8, 18, 38));
        character_list.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        main.add(character_list);
        character_list.setBounds(50, 100, 1170, 220);

        root.add(main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_pathMouseClicked

    private void home_pathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseEntered
        // TODO add your handling code here:
        home_path.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_home_pathMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel character_list;
    private utils.helper.RopaLabel guide_path1;
    private utils.helper.RopaLabel home_path;
    private javax.swing.JPanel main;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
