/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myAccount;

import editProfile.Edit_profile;
import home.Home;
import javax.swing.*;
import java.awt.Cursor;
import java.sql.SQLException;
import myCombo.MyCombo;
import utils.helper.Db;
import utils.helper.Session;
import java.sql.ResultSet;

/**
 *
 * @author Dammar
 */
public class MyAccount extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private void getFavoriteData() {
        Db db = new Db();
        try {
            db.connect();
            int user_id = Session.getId();
            String q = "SELECT \n"
                    + "    fc.id AS favorite_id,\n"
                    + "    c.name AS character_name,\n"
                    + "    cl.name_move\n"
                    + "FROM \n"
                    + "    favorite_combo fc\n"
                    + "JOIN \n"
                    + "    combo_list cl ON fc.combo_id = cl.id\n"
                    + "JOIN \n"
                    + "    character c ON cl.character_id = c.id\n"
                    + "WHERE \n"
                    + "    fc.user_id = :user_id\n"
                    + "LIMIT 1;";
            ResultSet res_combo = db.executeQuery(q, user_id);
            while (res_combo.next()) {

            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                db.disconnect();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public MyAccount() {
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        nickname.setText(Session.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        myCombo = new utils.helper.RoundedPanel();
        ropaLabel6 = new utils.helper.RopaLabel();
        jLabel3 = new javax.swing.JLabel();
        editProfile = new utils.helper.RoundedPanel();
        ropaLabel5 = new utils.helper.RopaLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nickname = new utils.helper.RopaLabel();
        MyAccount_path = new utils.helper.RopaLabel();
        home_path = new utils.helper.RopaLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1281, 650));
        setResizable(false);

        main.setBackground(new java.awt.Color(8, 18, 38));
        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 650));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myCombo.setBackground(new java.awt.Color(123, 15, 58));
        myCombo.setPreferredSize(new java.awt.Dimension(280, 280));
        myCombo.setRoundBottomLeft(50);
        myCombo.setRoundBottomRight(50);
        myCombo.setRoundTopLeft(50);
        myCombo.setRoundTopRight(50);
        myCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myComboMouseEntered(evt);
            }
        });
        myCombo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ropaLabel6.setText("My Combo");
        ropaLabel6.setFontSize(20.0F);
        myCombo.add(ropaLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/My_account.png"))); // NOI18N
        myCombo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 110, 80));

        main.add(myCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 280, 150));

        editProfile.setBackground(new java.awt.Color(123, 15, 58));
        editProfile.setPreferredSize(new java.awt.Dimension(280, 280));
        editProfile.setRoundBottomLeft(50);
        editProfile.setRoundBottomRight(50);
        editProfile.setRoundTopLeft(50);
        editProfile.setRoundTopRight(50);
        editProfile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                editProfileComponentRemoved(evt);
            }
        });
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
        });
        editProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ropaLabel5.setText("Edit Profile");
        ropaLabel5.setFontSize(20.0F);
        editProfile.add(ropaLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/normal/edit_profile.png"))); // NOI18N
        editProfile.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        main.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 290, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/character/128x128/profile.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        nickname.setText("Nickname");
        nickname.setFontSize(23.0F);
        main.add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        MyAccount_path.setText("/ My Account");
        MyAccount_path.setFontSize(20.0F);
        MyAccount_path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAccount_pathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccount_pathMouseEntered(evt);
            }
        });
        main.add(MyAccount_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, -1));

        home_path.setText("Home  ");
        home_path.setFontSize(20.0F);
        home_path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_pathMouseEntered(evt);
            }
        });
        main.add(home_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jMenu2.setText("Account");

        jMenuItem1.setText("My Account");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void editProfileComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_editProfileComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileComponentRemoved

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
        Edit_profile edit_profile = new Edit_profile();
        edit_profile.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_editProfileMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MyAccount_pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccount_pathMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccount_pathMouseClicked

    private void MyAccount_pathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccount_pathMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccount_pathMouseEntered

    private void home_pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_pathMouseClicked

    private void home_pathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pathMouseEntered
        // TODO add your handling code here:
        home_path.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_home_pathMouseEntered

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        // TODO add your handling code here:
        editProfile.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_editProfileMouseEntered

    private void myComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myComboMouseClicked
        // TODO add your handling code here:
        MyCombo myCombo = new MyCombo();
        myCombo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myComboMouseClicked

    private void myComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myComboMouseEntered
        // TODO add your handling code here:
        myCombo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myComboMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.helper.RopaLabel MyAccount_path;
    private utils.helper.RoundedPanel editProfile;
    private utils.helper.RopaLabel home_path;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel main;
    private utils.helper.RoundedPanel myCombo;
    private utils.helper.RopaLabel nickname;
    private utils.helper.RopaLabel ropaLabel5;
    private utils.helper.RopaLabel ropaLabel6;
    // End of variables declaration//GEN-END:variables
}
