/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guide;

import javax.swing.JFrame;
import java.util.*;
import javax.swing.ImageIcon;
import utils.helper.ScrollBar;

/**
 *
 * @author Dammar
 */
public class Character extends javax.swing.JFrame {

    /**
     * Creates new form Guide
     */
    public Character() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        ArrayList<ImageIcon> img = new ArrayList<>();
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/1.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        img.add(new ImageIcon(getClass().getResource("/image/button/32x32/2.png")));
        Object[][] data = {
            {img, "John", "1", "a", "ab", "c"},
            {img, "John", "1", "a", "ab", "c"},
            {img, "John", "1", "a", "ab", "c"},
            {img, "John", "1", "a", "ab", "c"},
            {img, "John", "1", "a", "ab", "c"},
            {img, "John", "1", "a", "ab", "c"}
        };
        movesheetTable1.setData(data);
        ScrollBar scrollPane = new ScrollBar(root);
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBar(null);
        scrollPane.getVerticalScrollBar().setUnitIncrement(10);
        scrollPane.setBounds(0, 0, main.getWidth(), 650);
        add(scrollPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        home_path = new utils.helper.RopaLabel();
        guide_path = new utils.helper.RopaLabel();
        guide_path1 = new utils.helper.RopaLabel();
        back = new utils.helper.RoundedPanel();
        ropaLabel1 = new utils.helper.RopaLabel();
        character_image = new javax.swing.JPanel();
        difficulty = new utils.helper.RopaLabel();
        characterItem1 = new utils.helper.CharacterItem();
        character_abilites = new utils.helper.RoundedPanel();
        character_abilites_title = new utils.helper.RopaLabel();
        evasiveness = new javax.swing.JPanel();
        evasiveness_title = new utils.helper.RopaItalicLabel();
        evasiveness_value = new utils.helper.CharacterAbilitiesValue();
        mobility = new javax.swing.JPanel();
        mobility_title = new utils.helper.RopaItalicLabel();
        mobility_value = new utils.helper.CharacterAbilitiesValue();
        throw_game = new javax.swing.JPanel();
        throw_game_title = new utils.helper.RopaItalicLabel();
        throw_game_value = new utils.helper.CharacterAbilitiesValue();
        combo_damage = new javax.swing.JPanel();
        combo_damage_title = new utils.helper.RopaItalicLabel();
        combo_damage_value = new utils.helper.CharacterAbilitiesValue();
        wall_carry = new javax.swing.JPanel();
        wall_carry_title = new utils.helper.RopaItalicLabel();
        wall_carry_value = new utils.helper.CharacterAbilitiesValue();
        movesheet = new utils.helper.RoundedPanel();
        movesheet_title = new utils.helper.RopaLabel();
        movesheetTable1 = new utils.helper.MovesheetTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        root.setMinimumSize(new java.awt.Dimension(1281, 100));
        root.setPreferredSize(new java.awt.Dimension(1281, 1480));
        root.setLayout(new javax.swing.BoxLayout(root, javax.swing.BoxLayout.LINE_AXIS));

        main.setBackground(new java.awt.Color(8, 18, 38));
        main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main.setMinimumSize(new java.awt.Dimension(1281, 650));
        main.setPreferredSize(new java.awt.Dimension(1281, 1480));
        main.setLayout(null);

        home_path.setText("Home  / ");
        home_path.setFontSize(20.0F);
        main.add(home_path);
        home_path.setBounds(50, 50, 59, 22);

        guide_path.setText("/ Dragunov");
        guide_path.setFontSize(20.0F);
        main.add(guide_path);
        guide_path.setBounds(160, 50, 140, 22);

        guide_path1.setText("Guide");
        guide_path1.setFontSize(20.0F);
        main.add(guide_path1);
        guide_path1.setBounds(110, 50, 60, 22);

        back.setBackground(new java.awt.Color(123, 15, 58));
        back.setRoundBottomLeft(10);
        back.setRoundBottomRight(10);
        back.setRoundTopLeft(10);
        back.setRoundTopRight(10);
        back.setLayout(new java.awt.GridBagLayout());

        ropaLabel1.setText("<<  Back");
        ropaLabel1.setFontSize(20.0F);
        back.add(ropaLabel1, new java.awt.GridBagConstraints());

        main.add(back);
        back.setBounds(1060, 50, 117, 33);

        character_image.setBackground(new java.awt.Color(8, 18, 38));

        difficulty.setForeground(new java.awt.Color(243, 167, 18));
        difficulty.setText("Difficulty: Medium");
        difficulty.setFontSize(18.0F);

        javax.swing.GroupLayout character_imageLayout = new javax.swing.GroupLayout(character_image);
        character_image.setLayout(character_imageLayout);
        character_imageLayout.setHorizontalGroup(
            character_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(character_imageLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(character_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        character_imageLayout.setVerticalGroup(
            character_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(character_imageLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(characterItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(character_image);
        character_image.setBounds(70, 110, 219, 225);

        character_abilites.setBackground(new java.awt.Color(66, 21, 50));
        character_abilites.setRoundBottomLeft(20);
        character_abilites.setRoundBottomRight(20);
        character_abilites.setRoundTopLeft(20);
        character_abilites.setRoundTopRight(20);
        character_abilites.setLayout(null);

        character_abilites_title.setText("| Character Abilities");
        character_abilites.add(character_abilites_title);
        character_abilites_title.setBounds(20, 20, 190, 27);

        evasiveness.setBackground(new java.awt.Color(66, 21, 50));
        evasiveness.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        evasiveness_title.setText("Evasiveness");
        evasiveness_title.setFontSize(20.0F);
        evasiveness.add(evasiveness_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

        evasiveness_value.setValue(5);
        evasiveness.add(evasiveness_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        character_abilites.add(evasiveness);
        evasiveness.setBounds(20, 60, 405, 65);

        mobility.setBackground(new java.awt.Color(66, 21, 50));
        mobility.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobility_title.setText("Mobility");
        mobility_title.setFontSize(20.0F);
        mobility.add(mobility_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

        mobility_value.setValue(6);
        mobility.add(mobility_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        character_abilites.add(mobility);
        mobility.setBounds(20, 130, 405, 65);

        throw_game.setBackground(new java.awt.Color(66, 21, 50));
        throw_game.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        throw_game_title.setText("Throw Game");
        throw_game_title.setFontSize(20.0F);
        throw_game.add(throw_game_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

        throw_game_value.setValue(8);
        throw_game.add(throw_game_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        character_abilites.add(throw_game);
        throw_game.setBounds(20, 200, 405, 65);

        combo_damage.setBackground(new java.awt.Color(66, 21, 50));
        combo_damage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo_damage_title.setText("Combo Damage");
        combo_damage_title.setFontSize(20.0F);
        combo_damage.add(combo_damage_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 130, -1));

        combo_damage_value.setValue(8);
        combo_damage.add(combo_damage_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        character_abilites.add(combo_damage);
        combo_damage.setBounds(450, 60, 405, 65);

        wall_carry.setBackground(new java.awt.Color(66, 21, 50));
        wall_carry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wall_carry_title.setText("Wall Carry");
        wall_carry_title.setFontSize(20.0F);
        wall_carry.add(wall_carry_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

        wall_carry_value.setValue(9);
        wall_carry.add(wall_carry_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        character_abilites.add(wall_carry);
        wall_carry.setBounds(450, 130, 405, 65);

        main.add(character_abilites);
        character_abilites.setBounds(290, 130, 890, 290);

        movesheet.setBackground(new java.awt.Color(66, 21, 50));
        movesheet.setRoundBottomLeft(20);
        movesheet.setRoundBottomRight(20);
        movesheet.setRoundTopLeft(20);
        movesheet.setRoundTopRight(20);

        movesheet_title.setText("| Move sheet");

        javax.swing.GroupLayout movesheetLayout = new javax.swing.GroupLayout(movesheet);
        movesheet.setLayout(movesheetLayout);
        movesheetLayout.setHorizontalGroup(
            movesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movesheetLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(movesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movesheetTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movesheet_title, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        movesheetLayout.setVerticalGroup(
            movesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movesheetLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(movesheet_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(movesheetTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        main.add(movesheet);
        movesheet.setBounds(80, 460, 1100, 450);

        root.add(main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Character().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.helper.RoundedPanel back;
    private utils.helper.CharacterItem characterItem1;
    private utils.helper.RoundedPanel character_abilites;
    private utils.helper.RopaLabel character_abilites_title;
    private javax.swing.JPanel character_image;
    private javax.swing.JPanel combo_damage;
    private utils.helper.RopaItalicLabel combo_damage_title;
    private utils.helper.CharacterAbilitiesValue combo_damage_value;
    private utils.helper.RopaLabel difficulty;
    private javax.swing.JPanel evasiveness;
    private utils.helper.RopaItalicLabel evasiveness_title;
    private utils.helper.CharacterAbilitiesValue evasiveness_value;
    private utils.helper.RopaLabel guide_path;
    private utils.helper.RopaLabel guide_path1;
    private utils.helper.RopaLabel home_path;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mobility;
    private utils.helper.RopaItalicLabel mobility_title;
    private utils.helper.CharacterAbilitiesValue mobility_value;
    private utils.helper.RoundedPanel movesheet;
    private utils.helper.MovesheetTable movesheetTable1;
    private utils.helper.RopaLabel movesheet_title;
    private javax.swing.JPanel root;
    private utils.helper.RopaLabel ropaLabel1;
    private javax.swing.JPanel throw_game;
    private utils.helper.RopaItalicLabel throw_game_title;
    private utils.helper.CharacterAbilitiesValue throw_game_value;
    private javax.swing.JPanel wall_carry;
    private utils.helper.RopaItalicLabel wall_carry_title;
    private utils.helper.CharacterAbilitiesValue wall_carry_value;
    // End of variables declaration//GEN-END:variables
}
